name: Github Pages
'on':
  push:
    branches:
      - main
    paths-ignore:
      - 'projects/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm ci
          npm run build -- --configuration=production --base-href https://apps.coturiv.fyi
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/coturiv.github.io
          force_orphan: true
          cname: apps.coturiv.fyi
